microservice:
  name: my-ip-server
  namespace: my-ip-app
  replicas: 3
  component: server
  appName: my-ip-app

workload:
  image: scophee/my-ip-server:1.5
  port: 8100
  containerPort: 8100

appEnvironment:
  FRONTEND_URL: 'http://k8s-mysharedgroup1-4ecbb1e167-1920773454.us-east-1.elb.amazonaws.com'
  TRUSTED_PROXIES: '192.168.0.0/16'
  APP_ENV: 'prod'
  PORT: '8100'