apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}

spec:
  replicas: {{ .Values.microservice.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.microservice.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.microservice.appName }}
        app.kubernetes.io/instance:  {{ .Values.microservice.name }}
        app.kubernetes.io/component:  {{ .Values.microservice.component }}

    spec:
      containers:
      - name:  {{ .Values.microservice.name }}
        image:  {{ .Values.workload.image }}
        resources:
          requests:
            cpu: "50m"
            memory: "80Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - containerPort:  {{ .Values.workload.containerPort }}