apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
  
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Values.microservice.appName }}
    app.kubernetes.io/instance: {{ .Values.microservice.name }}
  ports:
    - name: postgres
      port: {{ .Values.workload.port }}
      targetPort: {{ .Values.workload.port }}
